### ISSUE TITLE
Related Work - H-UPPAAL

### ISSUE THREAD

**Issue by Casperbart** [tgunde13/SW9ecdar#119]

**Comment by Casperbart** [comment]
- [ ] 1. Review
- [ ] 2. Review

**Comment by Casperbart** [comment]
Gerne lav et ekstra tjek efter de seneste rettelser. Smid gerne dette issue på done hvis den er helt færdig
- [ ] Ekstra review

**Comment by Rene4100** [comment]
Jeg tænker at det vil være godt hvis @tgunde13 ser afsnittet igennem
